### ISSUE TITLE
'Module not found: Error: Can't resolve' when using storage.helper

### ISSUE THREAD

**Issue by wannevancamp** [FriendsOfShopware/shopware-storefront-sdk#5]
### Question

I'm trying to use the `shopware-storefront-sdk` for the first time. After running `bin/build-storefront.sh` the following error is thrown:
```
Module not found: Error: Can't resolve '@friendsofshopware/storefront-types/declare/helper/storage.helper'
```

Is there some configuration missing in the README.md or am I doing something wrong? This is how my extension is set up. The main goal is to use the CookieStorageHelper in both 6.5 and 6.6 so that only one version needs to be maintained.

- Resources/app/storefront/build/webpack.config.js
```js
module.exports = (params) => {
    return {
        resolve: {
            modules: [
                `${params.basePath}/Resources/app/storefront/node_modules`,
            ],
        }
    };
}
```

- Resources/app/storefront/package.json
```
{
  "dependencies": {
    "@friendsofshopware/storefront-types": "^0.1.8"
  }
}
```

- Resources/app/storefront/tsconfig.json
```json
{
  "compilerOptions": {
    "types": ["@friendsofshopware/storefront-types"],
    "target": "ES2020",
    "module": "CommonJS"
  }
}
```

- Plugin class:
```js
import CookieStorageHelper from '@friendsofshopware/storefront-types/declare/helper/storage.helper';

export default class MyPlugin extends window.PluginBaseClass {

init() {
   if(CookieStorageHelper.getItem('cookie-name')){}
}
```

**Comment by shyim** [comment]
I would recommend to use window.localStorage thats kinda what the storage helper is doing

**Comment by wannevancamp** [comment]
We needed the functionality of the [cookie-storage.helper.js](https://github.com/shopware/shopware/blob/trunk/src/Storefront/Resources/app/storefront/src/helper/storage/cookie-storage.helper.js) which uses `document.cookie` instead of `window.localStorage`. Anyway, we have copied the cookie-storage.helper.js to our plugin to make es_build work. 

At first, I thought that the cookie-storage.helper.js helper class was included in this package, that's why I was confused. Probably this can be a useful addition when working with cookies.
